sudo: false

language: python

python: 
	- '2.7'

services: 
	- mysql

cache: pip

install:
  - pip install fabric
  - pip install -r server/learning/requirements.txt

before_script:
- mysql -e 'drop database if exists learndb;' -u root 
- mysql -e 'drop database if exists test_learndb;' -u root
- mysql -e 'create database learndb CHARACTER SET utf8 COLLATE utf8_general_ci;' -u root
- mysql -e 'create database test_learndb CHARACTER SET utf8 COLLATE utf8_general_ci;' -u root
- mysql -e 'grant all on learndb.* to 'admin'@'localhost' identified by 'admin@123#';' -u root
- mysql -e 'grant all on test_learndb.* to 'admin'@'localhost' identified by 'admin@123#';' -u root

script:
  - python server/learning/manage.py check

notifications:
  email: false