sudo: false

notifications:
  email: false

language: python
python: '2.7'
cache: pip

install:
  - pip install fabric
  - pip install -r server/learning/requirements.txt

script:
  - python server/learning/manage.py check