# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:37
from __future__ import unicode_literals

import datacenter.models.learning
import datacenter.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('mother_name', models.CharField(blank=True, max_length=50)),
                ('primary_email', models.CharField(max_length=250)),
                ('secondary_email', models.CharField(blank=True, max_length=250)),
                ('primary_mobile', models.CharField(max_length=20)),
                ('secondary_mobile', models.CharField(blank=True, max_length=20)),
                ('landline', models.CharField(blank=True, max_length=15)),
                ('door_no', models.CharField(blank=True, max_length=10)),
                ('street_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('locality', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('picture', models.ImageField(blank=True, storage=datacenter.storage.OverwriteStorage(), upload_to=datacenter.models.learning.profile_picture_name)),
                ('source_media', models.CharField(blank=True, max_length=250)),
                ('facebook_media', models.CharField(blank=True, max_length=250)),
                ('google_media', models.CharField(blank=True, max_length=250)),
                ('linkedin_media', models.CharField(blank=True, max_length=250)),
                ('twitter_media', models.CharField(blank=True, max_length=250)),
                ('created_by', models.CharField(blank=True, max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('school_college_name', models.CharField(blank=True, max_length=100)),
                ('year_passout', models.CharField(blank=True, max_length=4)),
                ('is_admin', models.BooleanField(default=0)),
                ('is_teacher', models.BooleanField(default=0)),
                ('is_member', models.BooleanField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
