from django.contrib.auth.models import User;
from datacenter.models import UserProfile;
user,status = User.objects.get_or_create(username='admin@insmartapps.com');
user.email = 'admin@insmartapps.com';
user.first_name = 'Kantanand';
user.last_name = 'US';
user.is_active = True;
user.is_superuser = True;
user.is_staff = True;
user.set_password('admin@123#');
user.save();
user_profile = UserProfile.objects.get(user=user);
user_profile.is_admin = True;
user_profile.first_name = user.first_name;
user_profile.last_name = user.last_name;
user_profile.email = user.email;
user_profile.save();
exit();
